# Login
val.username.password.invalid=Invalid username or password
val.authentication.success=Authentication successfully
val.password.expired.at.login.time=Password expired at login time
val.password.attempt.exceed=Password attempt limit exceeded
val.status.inactive.or.expected.reset=Account inactive or password reset required

#Cashier user
val.cashier.user.not.found = Cashier user not found

# Password reset
val.password.reset.success=Password reset successfully
val.application.user.not.found=User not found
val.application.user.password.policy.not.found=Password policy not found
val.application.user.otp.session.not.found=OTP session not found
val.application.user.otp.session.60s=Please wait 60 seconds before requesting another OTP
val.application.user.otp.send.success=OTP sent successfully
val.application.user.otp.exceed=OTP attempt limit exceeded
val.application.otp.not.found=OTP not found
val.application.otp.invalid.or.session.timeout=Invalid OTP or session timed out
val.application.otp.validation.success=OTP validation successful
val.otp.send.failed=Failed to send OTP

# Logout
val.logout.success=Logout successful.

# Billing
val.stock.not.found=Stock not found
val.insufficient.stock=Insufficient stock
val.item.cost.invalid=Invalid item cost
val.total.amount.invalid=Invalid total amount
val.cashier.not.found=Cashier not found
val.customer.not.found=Customer not found
val.billing.processed.success=Billing processed successfully
val.billing.stock.filter.list.success = Billing stock filter list successfully
val.billing.reference.date.success = Reference data retrieve successfully

# JWT/Auth
val.jwt.invalid.token=Invalid JWT token
val.jwt.validation.failed=JWT token validation failed
val.jwt.username.mismatch=Username in token does not match username in request body
val.jwt.token.mismatch=Token in request does not match stored token
val.jwt.internal.error=Internal server error during JWT processing

#Cash In/Out
val.cash.in.out.added.success = Cash {0} added successfully
val.cash.in.out.retrieve.success = Cash in/out retrieve successfully
val.opening.balance.retrieve.success = Opening balance retrieve successfully

